DEFAULT_ANDROID_SDK_ROOT = /opt/android/sdk
DEFAULT_ANDROID_NDK_ROOT = /opt/android/ndk
DEFAULT_ANDROID_PLATFORM = android-9
DEFAULT_ANDROID_NDK_HOST = linux-x86_64
DEFAULT_ANDROID_TARGET_ARCH = armeabi-v7a
DEFAULT_ANDROID_NDK_TOOLCHAIN_VERSION = 4.8
